/**
 * 资源路径常量表（由 arktsup resource gen 生成，请勿手改；资源变更后重新生成）
 */
export class R {
  /** string 资源路径 */
  static readonly strings: Record<string, string> = {
    'welcome': 'app.string.welcome',
  }
  /** color 资源路径 */
  static readonly colors: Record<string, string> = {
  }
  /** float 资源路径 */
  static readonly floats: Record<string, string> = {
  }
  /** media 资源路径 */
  static readonly media: Record<string, string> = {
  }
}
